# SPDX-License-Identifier: LGPL-2.1-or-later
# Copyright © 2019 ANSSI. All rights reserved.

# Vagrantfile to create the "clipos-testbed/ipsec-gw" box.

ENVNAME = "build_clipos-testbed"

Vagrant.configure("2") do |config|

  # Common settings for the libvirt provider
  config.vm.provider "libvirt" do |libvirt|
    # Do not use the directory name in which this Vagrantfile sits as prefix
    # to the libvirt domains:
    libvirt.default_prefix = "#{ENVNAME}"

    # Use QEMU/KVM as the libvirt driver:
    libvirt.driver = "kvm"
  end

  # Disable default synced_folder configuration
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "ipsec-gw" do |ipsecgw|
    ipsecgw.vm.box = "debian/buster64"

    # Do not automatically change the SSH keypair for a newly generated key pair
    # otherwise we would need to re-embed the default insecure Vagrant SSH key
    # pair in the final image:
    #
    # SECURITY WARNING: This is insecure but tolerated here because we are
    # expecting to create another Vagrant box from the VM we are creating out of
    # this Vagrantfile.
    config.ssh.insert_key = false

    # Provider-specific settings for this VM:
    ipsecgw.vm.provider "libvirt" do |libvirt|
      libvirt.cpus = 4
      libvirt.cputopology sockets: "1", cores: "2", threads: "2"
      libvirt.memory = 2048
      libvirt.graphics_type = "spice"
      libvirt.video_type = "qxl"
    end

    # rsync the /vagrant folder rather than using NFS
    ipsecgw.vm.synced_folder "./synced_folders/ipsec-gw", "/vagrant/", type:
      "rsync"

    # Provisioning:
    ipsecgw.vm.provision "shell", path: "provisioning/ipsec-gw.sh"
  end

end

# vim: set ft=ruby ts=2 sts=2 sw=2 et ai tw=79:
